name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x

    - name: Install & Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        RESPONSE_TYPE: ${{ secrets.RESPONSE_TYPE }}
        SCOPE: ${{ secrets.SCOPE }}
      run: |
        npm install
        npm run ng --build --prod --base-href=/oidc-implicit/

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./
        CLEAN: true
